name: Kelly Wang Portfolio
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
sass:
  style: compressed
include:
  - _projects
defaults:
  - scope:
      path: "_projects"
      # type: "projects"
    values:
      permalink: /:basename/project # make URL of pages in the folder _projects as on the root.
