name: Kelly Wang Portfolio
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
sass:
  style: compressed

# https://jekyllrb.com/docs/collections/
collections:
  projects:
    output: true
    permalink: /projects/:name # https://jekyllrb.com/docs/permalinks/#collections
